Revert "Directly link to functions available from Windows 7 onwards"
This reverts commit 07f6d25a00af112d46e939992fb9cf42879fc7c1.

Otherwise the x86_64 version doesn't compile with mingw-w64-crt 5.0.3.

Apparently those functions are absent in the libdwmapi.a library provided
by the CRT:
```
grep DwmSetIconicThumbnail /usr/x86_64-w64-mingw32/lib/libdwmapi.a
[no further output]
```

This leads to the following linker error:
```
x86_64-w64-mingw32-g++ -g -shared -Wl,-subsystem,windows -Wl,--out-implib,/build/mingw-w64-qt5-winextras/src/qtwinextras-everywhere-src-5.11.0/build-x86_64-w64-mingw32-shared/lib/libQt5WinExtras.dll.a -o ../../lib/Qt5WinExtras.dll object_script.Qt5WinExtras.Release  -lglu32 -lopengl32 -lgdi32 -luser32 -lQt5Gui -lQt5Core -lole32 -lshlwapi -lshell32 -ldwmapi
./.obj/release/qwinthumbnailtoolbar.o: In function `QWinThumbnailToolBarPrivate::updateIconicPixmapsEnabled(bool)':
/build/mingw-w64-qt5-winextras/src/qtwinextras-everywhere-src-5.11.0/src/winextras/qwinthumbnailtoolbar.cpp:246: undefined reference to `DwmInvalidateIconicBitmaps'
./.obj/release/qwinthumbnailtoolbar.o: In function `QWinThumbnailToolBarPrivate::updateIconicLivePreview(tagMSG const*)':
/build/mingw-w64-qt5-winextras/src/qtwinextras-everywhere-src-5.11.0/src/winextras/qwinthumbnailtoolbar.cpp:411: undefined reference to `DwmSetIconicLivePreviewBitmap'
./.obj/release/qwinthumbnailtoolbar.o: In function `QWinThumbnailToolBarPrivate::updateIconicThumbnail(tagMSG const*)':
/build/mingw-w64-qt5-winextras/src/qtwinextras-everywhere-src-5.11.0/src/winextras/qwinthumbnailtoolbar.cpp:396: undefined reference to `DwmSetIconicThumbnail'
collect2: error: ld returned 1 exit status
```

Note that the i686 version has the required functions and links fine:
```
grep DwmSetIconicThumbnail /usr/i686-w64-mingw32/lib/libdwmapi.a
Binary file /usr/i686-w64-mingw32/lib/libdwmapi.a matches
```